name: Build and Push-CI

on: 
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  issues: write

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
  # strategy:
    # matrix:
      # node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup node | ${{ matrix.node }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
      #  node-version: ${{ matrix.node }}
          node-version: '22'
          cache: 'npm'

      - run: npm ci
      - run: npm test

      - name: Generate Tags
        id: generate-tags
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "SHA=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::741448934450:role/ecr_role'
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build
        id: build-docker-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.generate-tags.outputs.SHA }}
        run: |
          docker build -t $REGISTRY/devops-ecr-ci:$TAG .
          docker push $REGISTRY/devops-ecr-ci:$TAG
          IMAGE=$(echo $REGISTRY/devops-ecr-ci:$TAG)
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Deploy to app runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: devops-ecr-api
          image: ${{ steps.build-docker-image.outputs.image }}
          access-role-arn: arn:aws:iam::741448934450:role/app-runner-role
          region: us-east-1
          cpu: 1
          memory: 2G
          port: 3000

      # - name: Push Docker Image
      #   run: |
      #     docker push cyberplank/devops-ci-api:${{ steps.generate-tags.outputs.SHA }}