name: Build and Push CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: npm ci
      - run: npm test

      - name: Generate Tags
        id: generate-tags
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "SHA=$SHA" >> $GITHUB_OUTPUT
          echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t devops-ci-api:${{ steps.generate-tags.outputs.SHA }} .