name: Build and Push-CI

on: 
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
#  issues: write

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
  # strategy:
    # matrix:
      # node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup node | ${{ matrix.node }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
      #  node-version: ${{ matrix.node }}
          node-version: '22'
          cache: 'npm'

      - run: npm ci
      - run: npm test

      - name: Generate Tags
        id: generate-tags
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "SHA=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::741448934450:role/ecr_role'
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #   #  registry: ghcr.io
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and Push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: cyberplank/devops-ci-api:${{ steps.generate-tags.outputs.SHA }}, cyberplank/devops-ci-api:latest

      # - name: Build Docker Image
      #   run: |
      #     docker build -t cyberplank/devops-ci-api:${{ steps.generate-tags.outputs.SHA }} .

      # - name: Push Docker Image
      #   run: |
      #     docker push cyberplank/devops-ci-api:${{ steps.generate-tags.outputs.SHA }}