name: Build and Push CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
  # strategy:
    # matrix:
      # node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup node | ${{ matrix.node }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
      #  node-version: ${{ matrix.node }}
          node-version: '22'
          cache: 'npm'

      - run: npm ci
      - run: npm test

      - name: Generate Tags
        id: generate-tags
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "SHA=$SHA" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t devops-ci-api:${{ steps.generate-tags.outputs.SHA }} .

      - name: Push Docker Image
        run: |
          docker push devops-ci-api:${{ steps.generate-tags.outputs.SHA }}